-- End-to-end scenario using the real sample plans + STVs (fixtures generated by scripts/gen-sql-fixtures.ts).
-- Sites: 1 Jahra, 2 Egaila, 3 Salmiya, 4 Hawally, 5 Jahra DC

create function public.t_assert(cond boolean, msg text) returns void language plpgsql as $$
begin
  if cond is distinct from true then raise exception 'ASSERT FAILED: %', msg; end if;
end $$;
grant execute on function public.t_assert(boolean, text) to authenticated;

create function public.t_expect_error(p_sql text, p_like text) returns void language plpgsql as $$
begin
  execute p_sql;
  raise exception 'ASSERT FAILED: expected error like "%" from: %', p_like, p_sql;
exception when others then
  if sqlerrm not like '%' || p_like || '%' then
    if sqlerrm like 'ASSERT FAILED%' then raise; end if;
    raise exception 'ASSERT FAILED: expected error like "%" but got "%"', p_like, sqlerrm;
  end if;
end $$;
grant execute on function public.t_expect_error(text, text) to authenticated;

-- users
insert into auth.users (id, email) values
  ('00000000-0000-0000-0000-00000000000a', 'admin@test'),
  ('00000000-0000-0000-0000-00000000000b', 'viewer@test'),
  ('00000000-0000-0000-0000-000000000001', 'jahra@test'),
  ('00000000-0000-0000-0000-000000000002', 'egaila@test'),
  ('00000000-0000-0000-0000-000000000003', 'salmiya@test'),
  ('00000000-0000-0000-0000-000000000004', 'hawally@test'),
  ('00000000-0000-0000-0000-000000000005', 'dc@test'),
  ('00000000-0000-0000-0000-0000000000ff', 'nobody@test');
insert into public.profiles (user_id, full_name, role) values
  ('00000000-0000-0000-0000-00000000000a', 'HO Admin', 'admin'),
  ('00000000-0000-0000-0000-00000000000b', 'HO Viewer', 'viewer'),
  ('00000000-0000-0000-0000-000000000001', 'Jahra Sup', 'store'),
  ('00000000-0000-0000-0000-000000000002', 'Egaila Sup', 'store'),
  ('00000000-0000-0000-0000-000000000003', 'Salmiya Sup', 'store'),
  ('00000000-0000-0000-0000-000000000004', 'Hawally Sup', 'store'),
  ('00000000-0000-0000-0000-000000000005', 'DC Sup', 'store');
insert into public.user_sites values
  ('00000000-0000-0000-0000-000000000001', 1), ('00000000-0000-0000-0000-000000000002', 2),
  ('00000000-0000-0000-0000-000000000003', 3), ('00000000-0000-0000-0000-000000000004', 4),
  ('00000000-0000-0000-0000-000000000005', 5);
-- a few masterlist items with cost
insert into public.items (item_code, name, cost) values ('1002710', 'Kdd CHOCOLATE MILK 250ml', 0.120), ('3005748', 'Dac All in One', 1.450);

-- ============ Plans: only HO can create ============
select set_config('request.jwt.claim.sub', '00000000-0000-0000-0000-000000000001', false);
set role authenticated;
select public.t_expect_error($$select public.create_allocation((select data from public.test_fx where name = 'plan_jahra'))$$, 'NOT_ALLOWED');
reset role;

select set_config('request.jwt.claim.sub', '00000000-0000-0000-0000-00000000000a', false);
set role authenticated;
select public.t_assert((public.create_allocation((select data from public.test_fx where name = 'plan_jahra'))->>'ref') = 'AL-00001', 'first plan ref');
select public.t_assert((public.create_allocation((select data from public.test_fx where name = 'plan_dc'))->>'ref') = 'AL-00002', 'dc plan ref');
select public.t_assert((select kind from public.allocations where ref = 'AL-00002') = 'dc', 'dc plan kind');
select public.t_assert((select count(*) from public.v_legs where ref = 'AL-00001') = 3, 'internal plan has 3 legs');
select public.t_assert((select planned_skus from public.v_legs where ref = 'AL-00001' and to_site_id = 4) = 32, 'Hawally leg 32 SKUs');
select public.t_assert((select status from public.v_legs where ref = 'AL-00001' and to_site_id = 4) = 'awaiting_dispatch', 'awaiting dispatch');
reset role;

-- ============ Dispatch STVs ============
-- Hawally may not upload Jahra's dispatch
select set_config('request.jwt.claim.sub', '00000000-0000-0000-0000-000000000004', false);
set role authenticated;
select public.t_expect_error($$select public.submit_stv((select data from public.test_fx where name = 'stv_39126'))$$, 'NOT_ALLOWED');
reset role;

select set_config('request.jwt.claim.sub', '00000000-0000-0000-0000-000000000001', false);
set role authenticated;
do $$
declare pv jsonb := public.stv_preview((select data from public.test_fx where name = 'stv_39126'));
begin
  perform public.t_assert(pv->>'direction' = 'dispatch', 'preview direction dispatch: ' || pv::text);
  perform public.t_assert((pv->>'can_submit')::boolean, 'jahra can submit');
  perform public.t_assert(jsonb_array_length(pv->'leg_suggestions') = 1, 'one leg suggested');
  perform public.t_assert(pv->'leg_suggestions'->0->>'ref' = 'AL-00001', 'suggests AL-00001');
  perform public.t_assert((pv->'leg_suggestions'->0->>'overlap')::int = 28, 'overlap 28');
  perform public.submit_stv((select data from public.test_fx where name = 'stv_39126') || jsonb_build_object('leg_id', pv->'leg_suggestions'->0->>'leg_id'));
end $$;
do $$
declare pv jsonb := public.stv_preview((select data from public.test_fx where name = 'stv_39109'));
begin
  perform public.submit_stv((select data from public.test_fx where name = 'stv_39109') || jsonb_build_object('leg_id', pv->'leg_suggestions'->0->>'leg_id'));
end $$;
select public.t_expect_error($$select public.submit_stv((select data from public.test_fx where name = 'stv_39109'))$$, 'DUPLICATE');
reset role;

select set_config('request.jwt.claim.sub', '00000000-0000-0000-0000-000000000005', false);
set role authenticated;
do $$
declare pv jsonb := public.stv_preview((select data from public.test_fx where name = 'stv_40493'));
begin
  perform public.t_assert(pv->'leg_suggestions'->0->>'ref' = 'AL-00002', 'dc suggestion');
  perform public.submit_stv((select data from public.test_fx where name = 'stv_40493') || jsonb_build_object('leg_id', pv->'leg_suggestions'->0->>'leg_id'));
end $$;
reset role;

-- ============ Plan vs dispatch reconciliation (the findings from the analysis) ============
select set_config('request.jwt.claim.sub', '00000000-0000-0000-0000-00000000000b', false);
set role authenticated;
do $$
declare hleg uuid := (select leg_id from public.v_legs where ref = 'AL-00001' and to_site_id = 4);
        eleg uuid := (select leg_id from public.v_legs where ref = 'AL-00001' and to_site_id = 2);
begin
  perform public.t_assert((select array_agg(item_code order by item_code) from public.v_leg_items where leg_id = hleg and dispatch_status = 'not_sent')
                          = array['1208373', '1209820', '3005622', '3005748'], 'Hawally: 4 not sent');
  perform public.t_assert((select count(*) from public.v_leg_items where leg_id = hleg and dispatch_status = 'ok') = 28, 'Hawally: 28 ok');
  perform public.t_assert((select dispatch_status from public.v_leg_items where leg_id = eleg and item_code = '1001676') = 'not_sent', 'Perrier juice not sent');
  perform public.t_assert((select dispatch_status from public.v_leg_items where leg_id = eleg and item_code = '1002390') = 'unplanned', 'Perrier water unplanned');
  perform public.t_assert((select dispatch_gap from public.v_leg_items where leg_id = eleg and item_code = '1202024') = -4, 'Indomie short 4');
  perform public.t_assert((select dispatch_status from public.v_leg_items where leg_id = eleg and item_code = '1210044') = 'short', 'Green forest short');
  perform public.t_assert((select status from public.v_legs where leg_id = hleg) = 'in_transit', 'hawally leg in transit');
  perform public.t_assert((select open_issues from public.v_legs where leg_id = hleg) = 4, 'hawally 4 issues');
  perform public.t_assert((select status from public.v_legs where ref = 'AL-00001' and to_site_id = 3) = 'awaiting_dispatch', 'salmiya awaiting');
  perform public.t_assert((select open_qty from public.v_legs where ref = 'AL-00002' and to_site_id = 4) = 1144, 'dc->hawally open 1144');
  -- today (30-09) all three STVs are past the 1-day receiving SLA -> every open line is flagged
  perform public.t_assert((select count(*) from public.v_discrepancies where kind = 'receipt_short') = 28 + 16 + 64, 'overdue receipt lines flagged');
end $$;
reset role;

-- ============ Store visibility (RLS) ============
select set_config('request.jwt.claim.sub', '00000000-0000-0000-0000-000000000002', false); -- Egaila
set role authenticated;
select public.t_assert((select count(*) from public.stvs) = 1, 'egaila sees only its incoming STV');
select public.t_assert((select count(*) from public.allocations) = 2, 'egaila sees both plans (destination)');
select public.t_assert((select count(*) from public.allocation_legs) = 2, 'egaila sees only its own legs');
select public.t_assert((select count(distinct leg_id) from public.allocation_lines) = 2, 'egaila sees only its lines');
select public.t_assert((select count(*) from public.v_legs) = 2, 'v_legs filtered');
select public.t_assert((select count(*) from public.profiles) = 1, 'only own profile');
select public.t_assert((select count(*) from public.audit_log) = 0, 'no audit for stores');
reset role;
select set_config('request.jwt.claim.sub', '00000000-0000-0000-0000-000000000003', false); -- Salmiya
set role authenticated;
select public.t_assert((select count(*) from public.stvs) = 0, 'salmiya sees no STVs');
select public.t_assert((select count(*) from public.stv_lines) = 0, 'salmiya sees no STV lines');
reset role;
select set_config('request.jwt.claim.sub', '00000000-0000-0000-0000-0000000000ff', false); -- no profile
set role authenticated;
select public.t_assert((select count(*) from public.sites) = 0, 'no profile sees nothing');
select public.t_assert((select count(*) from public.items) = 0, 'no profile sees no items');
select public.t_expect_error($$select public.stv_preview('{}'::jsonb)$$, 'NOT_ALLOWED');
reset role;

-- ============ Receipts by Hawally (new ERP code 304 auto-mapped) ============
select set_config('request.jwt.claim.sub', '00000000-0000-0000-0000-000000000004', false);
set role authenticated;
do $$
declare
  r1 jsonb := (select data from public.test_fx where name = 'stv_39126');
  pv jsonb;
begin
  -- receipt of 39126: all lines, but chocolate milk 250 of 259, plus an item that was never dispatched
  r1 := jsonb_set(r1, '{doc_no}', '"R-39126"');
  r1 := jsonb_set(r1, '{stv_date}', '"2026-09-17"');
  r1 := r1 || jsonb_build_object('from_code', '502', 'from_name', 'Hawally Allocation', 'to_code', '304', 'to_name', 'Hawally D.S');
  r1 := jsonb_set(r1, '{lines}', (
    select jsonb_agg(case when x->>'item_code' = '1002710' then jsonb_set(x, '{qty}', '250') else x end) || jsonb_build_array(jsonb_build_object('item_code', '9999999', 'qty', 3))
    from jsonb_array_elements(r1->'lines') x));
  pv := public.stv_preview(r1);
  perform public.t_assert(pv->>'direction' = 'receipt', 'receipt direction: ' || pv::text);
  perform public.t_assert((pv->'to'->>'is_new')::boolean and (pv->'to'->>'site_id')::int = 4, 'guessed 304 = Hawally DS');
  perform public.t_assert(pv->'dispatch_suggestions'->0->>'doc_no' = '39126', 'suggest 39126 first: ' || (pv->'dispatch_suggestions')::text);
  perform public.submit_stv(r1 || jsonb_build_object('link_dispatch_ids', jsonb_build_array(pv->'dispatch_suggestions'->0->>'stv_id')));
end $$;
select public.t_assert((select kind from public.erp_locations where code = '304') = 'ds' and (select auto_created from public.erp_locations where code = '304'), '304 auto created');
do $$
declare r2 jsonb := (select data from public.test_fx where name = 'stv_40493');
begin
  r2 := r2 || jsonb_build_object('doc_no', 'R-40493', 'stv_date', '2026-09-27', 'from_code', '502', 'from_name', 'Hawally Allocation', 'to_code', '304', 'to_name', 'Hawally D.S');
  perform public.submit_stv(r2); -- no explicit link: matched oldest-first
end $$;
select public.t_assert((select sum(open_qty) from public.v_dispatch_items where doc_no = '39126') = 9, '39126 open 9');
select public.t_assert((select sum(open_qty) from public.v_dispatch_items where doc_no = '40493') = 0, '40493 fully received');
select public.t_assert((select status from public.v_legs where ref = 'AL-00002' and to_site_id = 4) = 'completed', 'dc->hawally completed');
select public.t_assert((select completed_date from public.v_legs where ref = 'AL-00002' and to_site_id = 4) = '2026-09-27', 'completed date');
select public.t_assert((select status from public.v_legs where ref = 'AL-00001' and to_site_id = 4) = 'partially_received', 'jahra->hawally partial');
select public.t_assert((select unmatched_qty from public.v_unmatched_receipts where item_code = '9999999') = 3, 'over receipt');
select public.t_assert((select count(*) from public.v_discrepancies where kind = 'receipt_short' and doc_no = '39126') = 1, 'one receipt short on 39126');
select public.t_assert((select count(*) from public.v_discrepancies where kind = 'receipt_over') = 1, 'one receipt over');
-- Hawally cannot explain Jahra's shortage
select public.t_expect_error($$select public.request_resolution(jsonb_build_object('kind','dispatch_short','leg_id',(select leg_id from public.v_legs where ref='AL-00001' and to_site_id=4),'item_code','3005748','reason_code','NO_STOCK'))$$, 'NOT_ALLOWED');
select public.request_resolution(jsonb_build_object('kind', 'receipt_short', 'stv_id', (select id from public.stvs where doc_no = '39126'),
  'item_code', '1002710', 'gap_qty', -9, 'reason_code', 'COUNT_DIFF', 'note', '9 pcs missing on arrival'));
-- store cannot approve
select public.t_expect_error($$select public.decide_resolution((select id from public.resolutions limit 1), true, 'ok')$$, 'NOT_ALLOWED');
reset role;

-- Jahra (sender) sees its dispatch as received even without access to Hawally's receipt STV
select set_config('request.jwt.claim.sub', '00000000-0000-0000-0000-000000000001', false);
set role authenticated;
select public.t_assert((select count(*) from public.stvs where direction = 'receipt') = 0, 'jahra cannot see receipt STV');
select public.t_assert((select sum(received_qty) from public.v_dispatch_items where doc_no = '39126') = 969, 'jahra sees received 969');
select public.request_resolution(jsonb_build_object('kind', 'dispatch_short', 'leg_id', (select leg_id from public.v_legs where ref = 'AL-00001' and to_site_id = 4),
  'item_code', '3005748', 'gap_qty', -10, 'reason_code', 'NO_STOCK'));
reset role;

-- ============ HO approvals ============
select set_config('request.jwt.claim.sub', '00000000-0000-0000-0000-00000000000a', false);
set role authenticated;
select public.t_expect_error($$select public.decide_resolution((select id from public.resolutions where item_code = '3005748'), false, '')$$, 'why');
select public.decide_resolution(id, true, 'ok') from public.resolutions where status = 'pending';
select public.t_assert((select open_qty from public.v_dispatch_items where doc_no = '39126' and item_code = '1002710') = 0, 'approved receipt short closes open qty');
select public.t_assert((select open_issues from public.v_legs where ref = 'AL-00001' and to_site_id = 4) = 3, '3 issues left');
select public.t_assert((select status from public.v_legs where ref = 'AL-00001' and to_site_id = 4) = 'discrepancy', 'hawally leg now discrepancy');
-- close the rest directly as HO
select public.close_discrepancy(jsonb_build_object('kind', 'dispatch_short', 'leg_id', leg_id, 'item_code', item_code, 'reason_code', 'NO_STOCK'))
from public.v_leg_items where leg_id = (select leg_id from public.v_legs where ref = 'AL-00001' and to_site_id = 4) and dispatch_status = 'not_sent' and resolution_status is null;
select public.t_assert((select status from public.v_legs where ref = 'AL-00001' and to_site_id = 4) = 'completed', 'hawally leg completed');

-- void the 40493 receipt -> back in transit; re-upload -> completed again
select public.void_stv((select id from public.stvs where doc_no = 'R-40493'), 'uploaded by mistake');
select public.t_assert((select status from public.v_legs where ref = 'AL-00002' and to_site_id = 4) = 'in_transit', 'void puts back in transit');
reset role;
select set_config('request.jwt.claim.sub', '00000000-0000-0000-0000-000000000004', false);
set role authenticated;
select public.submit_stv((select data from public.test_fx where name = 'stv_40493') || jsonb_build_object('doc_no', 'R-40493', 'stv_date', '2026-09-27', 'from_code', '502', 'from_name', 'Hawally Allocation', 'to_code', '304', 'to_name', 'Hawally D.S'));
select public.t_assert((select status from public.v_legs where ref = 'AL-00002' and to_site_id = 4) = 'completed', 're-upload after void completes');
reset role;

-- ============ Out-of-order upload + unplanned transfer (Egaila) ============
select set_config('request.jwt.claim.sub', '00000000-0000-0000-0000-000000000002', false);
set role authenticated;
select public.submit_stv(jsonb_build_object('doc_no', 'R-E1', 'stv_date', '2026-09-20', 'from_code', '505', 'from_name', 'Egaila Allocation',
  'to_code', '305', 'to_name', 'Egaila D.S', 'lines', jsonb_build_array(jsonb_build_object('item_code', '1111111', 'qty', 5))));
select public.t_assert((select unmatched_qty from public.v_unmatched_receipts where doc_no = 'R-E1') = 5, 'receipt before dispatch is unmatched');
reset role;
select set_config('request.jwt.claim.sub', '00000000-0000-0000-0000-000000000001', false);
set role authenticated;
select public.submit_stv(jsonb_build_object('doc_no', 'D-J2', 'stv_date', '2026-09-19', 'from_code', '303', 'from_name', 'Jahraa D.S',
  'to_code', '505', 'to_name', 'Egaila Allocation', 'lines', jsonb_build_array(jsonb_build_object('item_code', '1111111', 'qty', 5))));
reset role;
select set_config('request.jwt.claim.sub', '00000000-0000-0000-0000-00000000000a', false);
set role authenticated;
select public.t_assert((select count(*) from public.v_unmatched_receipts where doc_no = 'R-E1') = 0, 'late dispatch upload gets matched');
select public.t_assert((select count(*) from public.v_discrepancies where kind = 'unplanned_stv' and doc_no = 'D-J2') = 1, 'unplanned STV flagged');
-- 39109 is still fully open at Egaila Allocation (never received) -> past SLA -> receipt_short rows
select public.t_assert((select count(*) from public.v_discrepancies where kind = 'receipt_short' and doc_no = '39109') = 16, '39109 overdue lines');

-- ============ Virtual Store Watch ============
select public.upload_snapshot(jsonb_build_object('location_code', '505', 'snapshot_date', '2026-09-28', 'rows', jsonb_build_array(
  jsonb_build_object('item_code', '1000987', 'qty', 160),      -- explained by 39109
  jsonb_build_object('item_code', '1011248', 'qty', 10),       -- 39109 says 14 -> receipt done in ERP but not uploaded
  jsonb_build_object('item_code', '7777777', 'qty', 40, 'since_date', '2025-03-01')  -- old backlog
)));
select public.t_assert((select match_status from public.v_vs_latest where location_code = '505' and item_code = '1000987') = 'explained', 'vs explained');
select public.t_assert((select match_status from public.v_vs_latest where location_code = '505' and item_code = '1011248') = 'receipt_not_uploaded', 'vs receipt not uploaded');
select public.t_assert((select match_status from public.v_vs_latest where location_code = '505' and item_code = '7777777') = 'not_in_system', 'vs backlog');
select public.t_assert((select since_date from public.v_vs_latest where item_code = '7777777') = '2025-03-01', 'backlog since date');
select public.t_assert((select count(*) from public.v_vs_latest where location_code = '505' and item_code = '1009878') = 1, 'in-system open items listed too');
select public.t_expect_error($$select public.upload_snapshot(jsonb_build_object('location_code','303','snapshot_date','2026-09-28','rows','[]'::jsonb))$$, 'not an Allocation');
select public.t_assert((select count(*) from public.audit_log) > 10, 'audit trail written');
reset role;

-- Hawally cannot see Egaila's snapshot
select set_config('request.jwt.claim.sub', '00000000-0000-0000-0000-000000000004', false);
set role authenticated;
select public.t_assert((select count(*) from public.vs_snapshots) = 0, 'hawally cannot see egaila snapshot');
select public.t_expect_error($$select public.upload_snapshot(jsonb_build_object('location_code','505','snapshot_date','2026-09-29','rows','[]'::jsonb))$$, 'NOT_ALLOWED');
reset role;

-- ============ Reject -> store sees rejection -> explains again ============
select set_config('request.jwt.claim.sub', '00000000-0000-0000-0000-000000000001', false);
set role authenticated;
select public.request_resolution(jsonb_build_object('kind', 'dispatch_short', 'leg_id', (select leg_id from public.v_legs where ref = 'AL-00001' and to_site_id = 2),
  'item_code', '1202024', 'gap_qty', -4, 'reason_code', 'NO_STOCK'));
reset role;
select set_config('request.jwt.claim.sub', '00000000-0000-0000-0000-00000000000a', false);
set role authenticated;
select public.decide_resolution((select id from public.resolutions where item_code = '1202024' and status = 'pending'), false, 'Stock report shows 12 pcs at Jahra');
reset role;
select set_config('request.jwt.claim.sub', '00000000-0000-0000-0000-000000000001', false);
set role authenticated;
select public.t_assert((select resolution_status from public.v_leg_items li join public.v_legs l using (leg_id) where l.ref = 'AL-00001' and l.to_site_id = 2 and li.item_code = '1202024') = 'rejected', 'store sees rejection');
select public.t_assert((select decision_note from public.resolutions where item_code = '1202024') = 'Stock report shows 12 pcs at Jahra', 'store can read HO note');
select public.request_resolution(jsonb_build_object('kind', 'dispatch_short', 'leg_id', (select leg_id from public.v_legs where ref = 'AL-00001' and to_site_id = 2),
  'item_code', '1202024', 'gap_qty', -4, 'reason_code', 'NEAR_EXPIRY', 'note', 'remaining 12 pcs expire this week'));
select public.t_assert((select resolution_status from public.v_leg_items li join public.v_legs l using (leg_id) where l.ref = 'AL-00001' and l.to_site_id = 2 and li.item_code = '1202024') = 'pending', 'new explanation pending');
reset role;

-- ============ STV uploaded before its plan is linked when the plan is created ============
select set_config('request.jwt.claim.sub', '00000000-0000-0000-0000-000000000001', false);
set role authenticated;
select public.submit_stv(jsonb_build_object('doc_no', 'EARLY-1', 'stv_date', '2026-09-20', 'from_code', '303', 'from_name', 'Jahraa D.S',
  'to_code', '502', 'to_name', 'Hawally Allocation', 'lines', jsonb_build_array(jsonb_build_object('item_code', '5555555', 'qty', 4), jsonb_build_object('item_code', '5555556', 'qty', 2))));
select public.t_assert((select leg_id from public.stvs where doc_no = 'EARLY-1') is null, 'early STV has no plan yet');
reset role;
select set_config('request.jwt.claim.sub', '00000000-0000-0000-0000-00000000000a', false);
set role authenticated;
do $$
declare r jsonb;
begin
  r := public.create_allocation(jsonb_build_object(
    'from_site_id', 1, 'plan_date', '2026-09-25',
    'legs', jsonb_build_array(jsonb_build_object('to_site_id', 4, 'lines', jsonb_build_array(
      jsonb_build_object('item_code', '5555555', 'qty', 4),
      jsonb_build_object('item_code', '5555556', 'qty', 3))))));
  perform public.t_assert((r->>'linked_stvs')::int = 1, 'plan links early STV: ' || r::text);
end $$;
select public.t_assert((select l.status from public.v_legs l join public.stvs s on s.leg_id = l.leg_id where s.doc_no = 'EARLY-1') = 'in_transit', 'plan leg now on the way');
-- the receiving store sees plans coming to it, including not-yet-sent ones
reset role;
select set_config('request.jwt.claim.sub', '00000000-0000-0000-0000-000000000003', false); -- Salmiya
set role authenticated;
select public.t_assert((select count(*) from public.v_legs where to_site_id = 3 and status = 'awaiting_dispatch') >= 1, 'receiver sees incoming plan not sent yet');
reset role;
