-- IALC System - core schema
-- Stores (sites), ERP locations (incl. virtual "Allocation" stores), items, allocation plans,
-- STVs, receipt matching, discrepancy resolutions, virtual-store snapshots, audit log.

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- Reference data

create table public.sites (
  id          int generated by default as identity primary key,
  name        text not null unique,
  kind        text not null check (kind in ('ds', 'dc')),
  aliases     text[] not null default '{}',   -- normalised names used in Excel headers / ERP names
  sort_order  int not null default 0,
  active      boolean not null default true
);
comment on table public.sites is 'Physical dark stores and the DC. Users are attached to sites.';

create table public.erp_locations (
  code          text primary key,               -- ERP store number, e.g. 303, 502, 603
  erp_name      text not null,                  -- as printed on the STV, e.g. "Hawally Allocation"
  site_id       int not null references public.sites(id),
  kind          text not null check (kind in ('ds', 'dc', 'allocation')),
  auto_created  boolean not null default false, -- created automatically from an uploaded STV (HO should confirm)
  created_at    timestamptz not null default now()
);
comment on table public.erp_locations is 'ERP store codes. kind=allocation are the virtual in-transit stores.';

create table public.settings (
  key    text primary key,
  value  jsonb not null
);

create table public.reason_codes (
  code        text primary key,
  label       text not null,
  applies_to  text[] not null,  -- discrepancy kinds
  sort_order  int not null default 0,
  active      boolean not null default true
);

-- Secrets readable only by the service role (no RLS policies => no client access).
create table public.app_secrets (
  key    text primary key,
  value  text not null
);

-- ---------------------------------------------------------------------------
-- Users

create table public.profiles (
  user_id     uuid primary key references auth.users(id) on delete cascade,
  full_name   text not null,
  login       text,                    -- email / username shown in the admin screen
  role        text not null check (role in ('admin', 'viewer', 'store')),
  active      boolean not null default true,
  created_at  timestamptz not null default now()
);
comment on column public.profiles.role is 'admin = HO super access, viewer = HO read-only, store = store staff limited to their sites';

create table public.user_sites (
  user_id  uuid not null references public.profiles(user_id) on delete cascade,
  site_id  int not null references public.sites(id) on delete cascade,
  primary key (user_id, site_id)
);

-- ---------------------------------------------------------------------------
-- Items masterlist

create table public.items (
  item_code        text primary key,
  barcode          text,
  name             text,
  category         text,
  brand            text,
  uom              text,
  cost             numeric(14, 3),   -- KWD per piece
  shelf_life_days  int,
  active           boolean not null default true,
  updated_at       timestamptz not null default now()
);
create index items_barcode_idx on public.items (barcode);
create index items_name_idx on public.items using gin (to_tsvector('simple', coalesce(name, '')));

create table public.item_imports (
  id           bigint generated always as identity primary key,
  file_name    text,
  total_rows   int not null,
  inserted     int not null,
  updated      int not null,
  uploaded_by  uuid references public.profiles(user_id),
  uploaded_at  timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Allocation plans (what HO / commercial asked to move)

create sequence public.allocation_ref_seq start 1;

create table public.allocations (
  id              uuid primary key default gen_random_uuid(),
  ref             text not null unique default ('AL-' || lpad(nextval('public.allocation_ref_seq')::text, 5, '0')),
  kind            text not null check (kind in ('dc', 'internal')),
  from_site_id    int not null references public.sites(id),
  plan_date       date not null,
  title           text,
  notes           text,
  source_file     text,     -- storage path of the uploaded Excel
  status          text not null default 'active' check (status in ('active', 'cancelled')),
  created_by      uuid references public.profiles(user_id),
  created_at      timestamptz not null default now(),
  cancelled_by    uuid references public.profiles(user_id),
  cancelled_at    timestamptz,
  cancel_reason   text
);
create index allocations_from_idx on public.allocations (from_site_id, plan_date desc);

-- One leg per destination store.
create table public.allocation_legs (
  id              uuid primary key default gen_random_uuid(),
  allocation_id   uuid not null references public.allocations(id) on delete cascade,
  to_site_id      int not null references public.sites(id),
  unique (allocation_id, to_site_id)
);
create index allocation_legs_to_idx on public.allocation_legs (to_site_id);

create table public.allocation_lines (
  leg_id       uuid not null references public.allocation_legs(id) on delete cascade,
  item_code    text not null,
  item_name    text,
  barcode      text,
  planned_qty  numeric(14, 3) not null check (planned_qty > 0),
  primary key (leg_id, item_code)
);

-- ---------------------------------------------------------------------------
-- Stock Transfer Vouchers (what actually happened in the ERP)

create table public.stvs (
  id              uuid primary key default gen_random_uuid(),
  doc_no          text not null,
  stv_date        date not null,
  from_code       text not null references public.erp_locations(code),
  to_code         text not null references public.erp_locations(code),
  from_site_id    int not null references public.sites(id),
  to_site_id      int not null references public.sites(id),
  from_kind       text not null,
  to_kind         text not null,
  -- dispatch: DS/DC -> X Allocation ; receipt: X Allocation -> X DS ; direct: DS/DC -> DS/DC ; other: anything else
  direction       text not null check (direction in ('dispatch', 'receipt', 'direct', 'other')),
  leg_id          uuid references public.allocation_legs(id) on delete set null,
  post_ref        text,
  source          text not null default 'pdf' check (source in ('pdf', 'excel', 'manual')),
  file_path       text,
  file_name       text,
  line_count      int not null default 0,
  total_qty       numeric(14, 3) not null default 0,
  parse_warnings  text[] not null default '{}',
  status          text not null default 'active' check (status in ('active', 'void')),
  void_reason     text,
  voided_by       uuid references public.profiles(user_id),
  voided_at       timestamptz,
  uploaded_by     uuid references public.profiles(user_id),
  uploaded_at     timestamptz not null default now()
);
create unique index stvs_doc_no_active_uq on public.stvs (doc_no) where status = 'active';
create index stvs_to_idx on public.stvs (to_code, direction, status);
create index stvs_from_idx on public.stvs (from_code, direction, status);
create index stvs_leg_idx on public.stvs (leg_id);
create index stvs_sites_idx on public.stvs (from_site_id, to_site_id);

create table public.stv_lines (
  id          bigint generated always as identity primary key,
  stv_id      uuid not null references public.stvs(id) on delete cascade,
  line_no     int not null,
  item_code   text not null,
  barcode     text,
  item_name   text,
  pack_qty    numeric(14, 3) not null default 1,
  unit        text,
  qty         numeric(14, 3) not null check (qty > 0),
  exp_date    text
);
create index stv_lines_stv_idx on public.stv_lines (stv_id, item_code);
create index stv_lines_item_idx on public.stv_lines (item_code);

-- Receipt STV explicitly says which dispatch STV(s) it receives (user-confirmed suggestion).
create table public.stv_links (
  receipt_id   uuid not null references public.stvs(id) on delete cascade,
  dispatch_id  uuid not null references public.stvs(id) on delete cascade,
  primary key (receipt_id, dispatch_id)
);
create index stv_links_dispatch_idx on public.stv_links (dispatch_id);

-- Derived: how much of each dispatched item has been received (rebuilt by rebuild_matches()).
create table public.receipt_matches (
  id               bigint generated always as identity primary key,
  location_code    text not null,
  item_code        text not null,
  dispatch_id      uuid not null references public.stvs(id) on delete cascade,
  receipt_id       uuid not null references public.stvs(id) on delete cascade,
  receipt_date     date not null,
  receipt_doc_no   text not null,
  qty              numeric(14, 3) not null check (qty > 0)
);
create index receipt_matches_loc_idx on public.receipt_matches (location_code, item_code);
create index receipt_matches_dispatch_idx on public.receipt_matches (dispatch_id, item_code);
create index receipt_matches_receipt_idx on public.receipt_matches (receipt_id, item_code);

-- ---------------------------------------------------------------------------
-- Discrepancy resolutions: store gives a reason, HO approves / rejects.

create table public.resolutions (
  id              uuid primary key default gen_random_uuid(),
  kind            text not null check (kind in (
                    'dispatch_short',  -- sent less than planned (or not at all)
                    'dispatch_over',   -- sent more than planned
                    'unplanned_item',  -- item on the STV but not in the plan
                    'unplanned_stv',   -- whole STV without a plan
                    'receipt_short',   -- dispatched but not (fully) received
                    'receipt_over')),  -- received more than dispatched / without a dispatch record
  leg_id          uuid references public.allocation_legs(id) on delete cascade,
  stv_id          uuid references public.stvs(id) on delete cascade,
  item_code       text not null,        -- '*' for unplanned_stv
  gap_qty         numeric(14, 3),
  reason_code     text references public.reason_codes(code),
  note            text,
  status          text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  requested_by    uuid references public.profiles(user_id),
  requested_at    timestamptz not null default now(),
  decided_by      uuid references public.profiles(user_id),
  decided_at      timestamptz,
  decision_note   text,
  check (leg_id is not null or stv_id is not null)
);
-- only one live (pending/approved) resolution per discrepancy
create unique index resolutions_live_uq on public.resolutions (
  kind, coalesce(leg_id, '00000000-0000-0000-0000-000000000000'::uuid),
  coalesce(stv_id, '00000000-0000-0000-0000-000000000000'::uuid), item_code
) where status in ('pending', 'approved');
create index resolutions_status_idx on public.resolutions (status);

-- ---------------------------------------------------------------------------
-- Virtual Store Watch: ERP stock-on-hand of the Allocation stores

create table public.vs_snapshots (
  id              uuid primary key default gen_random_uuid(),
  location_code   text not null references public.erp_locations(code),
  snapshot_date   date not null,
  file_name       text,
  file_path       text,
  line_count      int not null default 0,
  total_qty       numeric(16, 3) not null default 0,
  uploaded_by     uuid references public.profiles(user_id),
  uploaded_at     timestamptz not null default now(),
  unique (location_code, snapshot_date)
);

create table public.vs_snapshot_lines (
  snapshot_id  uuid not null references public.vs_snapshots(id) on delete cascade,
  item_code    text not null,
  item_name    text,
  qty          numeric(14, 3) not null,
  value        numeric(16, 3),
  since_date   date,
  primary key (snapshot_id, item_code)
);

-- ---------------------------------------------------------------------------
-- Audit trail

create table public.audit_log (
  id         bigint generated always as identity primary key,
  at         timestamptz not null default now(),
  user_id    uuid,
  action     text not null,
  entity     text,
  entity_id  text,
  details    jsonb
);
create index audit_log_at_idx on public.audit_log (at desc);
